version: '3'

services:
   mongo:
     image: tutum/mongodb
     volumes:
       - ~/mongo/db:/data/db
     environment:
       AUTH: "no"
     ports:
       - "28017:28017"
       - "27017:27017"

   twitter_fetcher:
     depends_on:
       - mongo
     image: python_base_image:v1
     entrypoint: python fetchers/daq_twitter/twitter_fetcher.py
     volumes:
      - .:/opt/code
      - /tmp/logs:/tmp/logs
     links:
      - mongo

   news_api_fetcher:
     depends_on:
       - mongo
     image: python_base_image:v1
     entrypoint: python fetchers/daq_news/news_api_fetcher.py
     volumes:
           - .:/opt/code
           - /tmp/logs:/tmp/logs
     links:
      - mongo

   news_river_fetcher:
     depends_on:
       - mongo
     image: python_base_image:v1
     entrypoint: python fetchers/daq_news/news_river_fetcher.py
     volumes:
           - .:/opt/code
           - /tmp/logs:/tmp/logs
     links:
      - mongo

   development:
     depends_on:
       - mongo
     image: python_base_image:v1
     entrypoint: tail -f /dev/null
     volumes:
       - .:/opt/code
       - ../pyMABED:/opt/pyMABED
       - /tmp/logs:/tmp/logs
     links:
       - mongo